kind: Deployment
apiVersion: apps/v1
metadata:
  name: go-app
  namespace: order-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      name: go-app
      labels:
        app: go-app
    spec:
      containers:
      - name: 
        image: souvik741156/order-api:latest
        ports:
        - containerPort: 3000
