apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-app
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "order-app.local"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: go-app-svc
            port:
              number: 3000