apiVersion: v1
kind: Service
metadata:
  name: go-app-svc
  namespace: order-app
  labels:
    app: go-app
spec:
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 80        # svc port
      targetPort: 80  # Pod port
  type: NodePort
